#!/sbin/openrc-run

description="llama.cpp HTTP server"

command="/usr/bin/llama-server"
command_background="yes"
command_user="llama-server:llama-server"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
    need net
}

start_pre() {
    checkpath --directory --mode 0755 /run
    checkpath --directory --owner llama-server:llama-server --mode 0755 /var/lib/llama
    checkpath --directory --owner llama-server:llama-server --mode 0755 /var/lib/llama/models
    if [ -z "${LLAMA_LOG}" ]; then
    	eerror "LLAMA_LOG is not configured in /etc/conf.d/llama-server"
    	return 1
	fi
    checkpath --file --owner llama-server:llama-server --mode 0644 ${LLAMA_LOG}

    if [ -z "${LLAMA_MODEL}" ]; then
        eerror "LLAMA_MODEL is not configured in /etc/conf.d/llama-server"
        return 1
    fi

    if [ ! -f "${LLAMA_MODEL}" ]; then
        eerror "Model not found: ${LLAMA_MODEL}"
        return 1
    fi
}

command_args="-m ${LLAMA_MODEL} ${LLAMA_ARGS}"
